config/routes.rb
Rails.application.routes.draw do

  get 'tasks/index'

namespace :admin do
resources :tasks do
  collection do
    get 'search','user_report', 'time_report','resource_report', 'task_resource_report', 'delayed_tasks_report'
  end
end
end



namespace :admin do
  resources :users, :task_statuses, :tasks, :resources
end


#namespace :admin do
#  resources :tasks do
#    get 'search', on: :collection
#  end
#end

#resources :tasks, :only => [:search] do


#namespace :admin do
 # resources :tasks do
  #end
#end

#resources :users do
#  resources :tasks
#end

#root 'admin/users#index'
root 'sessions#new'

resource :sessions, only: [:create] 

=begin
#resource :users do
#get "/home", :to => "users#get_user_tasks"
#end
=end

#resource :users

resources :users do
  resources :tasks do
  end
end

resources :tasks do
    resource :comments
end


#get '/login', to: 'sessions#new'
#get '/logout', to: 'sessions#destroy'

  get    '/login',         to: 'sessions#new'
  post   '/login',         to: 'sessions#create'
  get    '/logout',        to: 'sessions#destroy'
  get    '/registration',  to: 'users#new'



end

app/controllers/admin/task_statuses_controller.rb
class Admin::TaskStatusesController < ApplicationController

	def index
		@statuses = TaskStatus.all
	end

	def show
		@status = TaskStatus.find(params[:id])
	end

	def new
		@status = TaskStatus.new
	end

	def edit
		@status = TaskStatus.find(params[:id])
	end

	def create
		@status = TaskStatus.new(task_status_params)
		if @status.save
			redirect_to admin_task_statuses_path
		else
			render 'New'
		end
	end

	def update
		@status  = TaskStatus.find(params[:id])
		if @status.update(task_status_params)
			redirect_to admin_task_statuses_path
		else
			render 'Edit'
		end
	end

	def destroy
		@status = TaskStatus.find(params[:id])
		@status.destroy
		redirect_to admin_task_statuses_path
	end

	private
	def task_status_params
		params.require(:task_status).permit(:name)
	end


end

app/helpers/admin/task_statuses_helper.rb
module Admin::TaskStatusesHelper
end

app/views/admin/task_statuses/edit.html.erb
<%= form_for :task_status, url: admin_task_statuses_path  do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <%= f.submit %>
  <% end %>

app/views/admin/task_statuses/index.html.erb
<h1>Task statuses index</h1>
<%= link_to 'New',  new_admin_task_status_path  %>
<table>
	<th>Name</th>
	<th>Action</th>
	<% @statuses.each do |status|%>
	<tr>
		<td><%= status.name %></td>
		<td><%= link_to 'Show' %></td>
		<td><%= link_to 'Edit',  edit_admin_task_status_path(status) %></td>
		<td><%= link_to 'Delete', admin_task_status_path(status), 
      	method: :delete,
      	data: {confirm: "Are You sure?"} %></td>
	</tr>
	<% end %>

app/views/admin/task_statuses/new.html.erb
<%= form_for :task_status, url: admin_task_statuses_path  do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <%= f.submit %>
  <% end %>