config/routes.rb
Rails.application.routes.draw do

  get 'tasks/index'

namespace :admin do
resources :tasks do
  collection do
    get 'search','user_report', 'time_report','resource_report', 'task_resource_report', 'delayed_tasks_report'
  end
end
end



namespace :admin do
  resources :users, :task_statuses, :tasks, :resources
end


#namespace :admin do
#  resources :tasks do
#    get 'search', on: :collection
#  end
#end

#resources :tasks, :only => [:search] do


#namespace :admin do
 # resources :tasks do
  #end
#end

#resources :users do
#  resources :tasks
#end

#root 'admin/users#index'
root 'sessions#new'

resource :sessions, only: [:create] 

=begin
#resource :users do
#get "/home", :to => "users#get_user_tasks"
#end
=end

#resource :users

resources :users do
  resources :tasks do
  end
end

resources :tasks do
    resource :comments
end


#get '/login', to: 'sessions#new'
#get '/logout', to: 'sessions#destroy'

  get    '/login',         to: 'sessions#new'
  post   '/login',         to: 'sessions#create'
  get    '/logout',        to: 'sessions#destroy'
  get    '/registration',  to: 'users#new'



end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user
	belongs_to :task_status
  has_many :comments
  has_many :used_resources
  #has_many :resources, :through => :used_resources
  has_many :subs, class_name: "Task", foreign_key: "parent_task_id" 
  belongs_to :parent, class_name: "Task"

  accepts_nested_attributes_for :used_resources
  #accepts_nested_attributes_for :resources

  validates_presence_of :name
  #validates_presence_of :estimate
  validates_presence_of :user_id
  
	scope :user_id, -> (user_id) { where user_id: user_id }
  scope :status, -> (task_status_id) { where task_status_id: task_status_id }
  scope :created_by, -> (user_id) { where created_by: user_id }
  scope :is_parent, -> (is_parent) {where is_parent: is_parent}
  scope :created_at_range, -> (start_date, end_date) { where "created_at > ? AND created_at < ? ",start_date.beginning_of_day, end_date.end_of_day}
  scope :delayed, -> {where "logged_time > estimate"}

end

app/controllers/admin/tasks_controller.rb
class Admin::TasksController < ApplicationController

  def index
    if params[:task_status_id]
      @tasks = Task.status(params[:task_status_id])  
    else
      @tasks = Task.all
    end
  end

  def show
    @task = Task.find(params[:id])
    if @task.parent_task_id 
      @parent = Task.find(@task.parent_task_id)
    else
      @parent = Task.new
    end
  end

  def new
    gon.resources = Resource.all
    @task = Task.new
    @task.used_resources.build
  end

  def edit
    @task = Task.find(params[:id])
  end

  def create 
    @task = Task.new(task_params)
    if @task.save
      redirect_to admin_tasks_path
    else
      render 'new'
    end
  end

  def update 
    @task = Task.find(params[:id])
      if @task.update(task_params)
        respond_to do | format |
        format.html do 
        render 'edit'
      end
      format.json do
        render json: @task.to_json 
      end
      end
        
    else
      render 'edit'
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to admin_tasks_path
  end

  def search
    #@tasks = Task.all   
    if params[:status] != nil
      @tasks = Task.status(params[:status][:task_status_id])
    end
  end

  def user_report
    if params[:user] != nil
      @tasks = Task.user_id(params[:user][:user_id])
    end
  end

  def time_report
    if params[:date_from] && params[:date_to]
      date_from = DateTime.parse(params[:date_from])
      date_to = DateTime.parse(params[:date_to])
      @tasks = Task.created_at_range(date_from, date_to)
    else
      @tasks = Task.all
    end
  end

  def resource_report
    if params[:date_from] && params[:date_to]
      date_from = DateTime.parse(params[:date_from])
      date_to = DateTime.parse(params[:date_to])
      @used_resources = UsedResource.created_at_range(date_from,date_to)
    else
      @used_resources = UsedResource.all
    end
  end

  def task_resource_report
    #@resources = UsedResource.all #zasto se ajax ne poziva sa ovim, a radi sa kodom ispod
    #kao da ga poziva tek kada vrati objekat ali zasto onda opet ne poziva jer je ovaj vratio se UR
    if params[:task] != nil
      @resources = UsedResource.used_for_task(params[:task][:task_id])
    end
  end

  def delayed_tasks_report
    @tasks = Task.delayed
  end


  private
    def task_params
      params.require(:task).permit(:name, :description, :logged_time, :parcent_done, :user_id, :task_status_id, :estimate, 
                                  :parent_task_id, :is_parent, :created_by, used_resources_attributes: [:resource_id, :used] ) 
    end

    def resources_params

      params.require(:used_resources).permit(:resource_id, :used)
      
    end
end
    

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  #before_action :find_record

  def index
    if params[:task_status_id]
      @tasks = current_user.tasks.status(params[:task_status_id])  
    else
      @tasks = Task.all
    end
  end

  def show
    @task = Task.find(params[:id])
    if @task.parent_task_id 
      @parent = Task.find(@task.parent_task_id)
    else
      @parent = Task.new
    end
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def create 
      @task = Task.new(task_params)
    if @task.save
      redirect_to user_tasks_path
    else
      render 'new'
    end
  end

  def update 
    @task = Task.find(params[:id])
      if @task.update(task_params)
        respond_to do | format |
        format.html do 
        redirect_to user_tasks_path 
      end
      format.json do
        render json: @task.to_json 
      end
      end
        
    else
      render 'edit'
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to admin_tasks_path
  end

  def search
  end
  
  private
    def task_params
      params.require(:task).permit(:description, :logged_time, :parcent_done, :user_id, :task_status_id)
    end
end
    

app/helpers/admin/tasks_helper.rb
module Admin::TasksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper

  def tasktest
    tasks.status(1).count
  end
end

app/views/admin/tasks/_resource_report.html.erb
<% if @tasks.count>0 %>     
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-success" style="display:none;">
                    <span class="glyphicon glyphicon-ok"></span> Drag table row and cange Order</div>
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                Task Name
                            </th>
                            <th>
                                Resource Name
                            </th>
                            <th>
                                Used Resources
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                      <% @used_resources.each do |resource| %>
                        <tr>
                            <td>
                                <%= resource.task.name %>
                            </td>
                            <td>
                                <%= resource.resource %>
                            </td>
                            <td>
                               <%= resource.used %> 
                            </td>
                        </tr> 
                        <% end %>            
                    </tbody>
                </table>
            </div>
        </div>
    </div>
<% else %>
    <div id = "search_results">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="alert alert-success" style="display:none;">
                        <span class="glyphicon glyphicon-ok"></span> Drag table row and cange Order</div>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    No Resources Were Used At Given Period
                                </th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/admin/tasks/_task_resource_report.html.erb
 
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-success" style="display:none;">
                    <span class="glyphicon glyphicon-ok"></span> Drag table row and cange Order</div>
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                Task Name
                            </th>
                            <th>
                                Description
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                      <% @resources.each do |resource| %>
                        <tr>
                            <td>
                                <%= resource.resource.name %>
                            </td>
                            <td>
                                <%= resource.used %>
                            </td>
                        </tr> 
                        <% end %>            
                    </tbody>
                </table>
            </div>
        </div>
    </div>

app/views/admin/tasks/_user_report.html.erb
<% if @tasks.count>0 %>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-success" style="display:none;">
                    <span class="glyphicon glyphicon-ok"></span> Drag table row and cange Order</div>
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                Task Name
                            </th>
                            <th>
                                Description
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                      <% @tasks.each do |task| %>
                        <tr>
                            <td>
                                <%= task.name %>
                            </td>
                            <td>
                                <%= task.description%>
                            </td>
                        </tr> 
                        <% end %>            
                    </tbody>
                </table>
            </div>
        </div>
   </div>
<% else %>
    <div id = "search_results">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="alert alert-success" style="display:none;">
                        <span class="glyphicon glyphicon-ok"></span> Drag table row and cange Order</div>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    No Tasks Assigned To User
                                </th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/admin/tasks/delayed_tasks_report.html.erb
<% if @tasks.count>0 %>    
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-success" style="display:none;">
                    <span class="glyphicon glyphicon-ok"></span> Drag table row and cange Order</div>
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                Task Name
                            </th>
                            <th>
                                Description
                            </th>
                            <th>
                                Estimate
                            </th>
                            <th>
                                Logged
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                      <% @tasks.each do |task| %>
                        <tr>
                            <td>
                                <%= task.name %>
                            </td>
                            <td>
                                <%= task.description %>
                            </td>
                            <td>
                               <%= task.estimate %> 
                            </td>
                            <td>
                               <%= task.logged_time %> 
                            </td>
                        </tr> 
                        <% end %>            
                    </tbody>
                </table>
            </div>
        </div>
    </div>
<% else %>
    <div id = "search_results">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="alert alert-success" style="display:none;">
                        <span class="glyphicon glyphicon-ok"></span> Drag table row and cange Order</div>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    All Tasks Are On Track
                                 </th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/admin/tasks/edit.html.erb
<div class="container">
  <div class="row task_form">
    <div class="col-xs-12 col-sm-8 col-md-4 col-md-offset-4">
      <div class="login-panel panel panel-default">
        <div class="panel-heading">Edit task</div>
          <div class="panel-body">
            <%= form_for @task, url:admin_task_path, method: :patch , html: {role: "form"} do |f| %>
              <fieldset>
                <div class="form-group">
                  <%= f.label :name %><br>
                  <%= f.text_field :name, class: "form-control" %>
                </div>
                  <div class="form-group">
                  <%= f.label :description %><br>
                  <%= f.text_field :description, class: "form-control" %>
                </div>
                <% if @task.is_parent == 0 %>
                <div class="form-group">
                  <%= f.label :estimate %><br>
                  <%= f.text_field :estimate, class: "form-control" %>
                </div>
                <div class="form-group">
                  <%= f.label :logged_time %><br>
                  <%= f.text_field :logged_time, class: "form-control" %>
                </div>
                <div class="form-group">
                  <%= f.label :parcent_done %><br>
                  <%= f.text_field :parcent_done, class: "form-control" %>
                </div>
                                <div class="form-group">
                  <%= f.label :created_at %><br>
                  <%= f.text_field :created_at, :value => nice_date_form(@task.created_at), class: "form-control" %>
                </div>
                <div class="form-group">
                	<%= f.label :user_id %>
                	<%= f.collection_select :user_id, User.all, :id, :first_name, {}, {class: "form-control" } %>
                </div>
                <div class="form-group">
                  <%= f.label :task_status_id %>
                  <%= f.collection_select :task_status_id, TaskStatus.all, :id, :name, {}, {class: "form-control" }  %>
                <div>
                <% end %>
                <%= f.submit :submit, {class: "btn btn-primary" } %>
              </fieldset>

             <!-- <%= f.fields_for :used_resources do |ff| %>
                <%= ff.label :resource_id, "Resource Name" %>
                <%= ff.collection_select :resource_id, Resource.all, :id, :name, {prompt: 'Add Resource'}, {class: "form-control" , id: "resources_dd"} %>
                <%= ff.label :used, "Used Resources" %>
                <%= ff.text_field :used, class: "form-control", min: "1", max: "200", placeholder: "Number" , :required => false %>
              <% end %>-->
              
            <% end %>
            <%= render "comments/comment" %>
          </div>
        </div>
      </div>
    </div><!-- /.col-->
  </div><!-- /.row -->
</div>

app/views/admin/tasks/index.html.erb
<!--<div class="ticket_container">-->
  <div class="container">
    <div class="row">
      <div class="col-lg-12 margin-bottom-20">
        <input type="search" class="form-control" id="input-search" placeholder="Search Tasks..." >
      </div>
    </div>
        <div class="row">
<div class="searchable-container">
  <% @tasks.each do |task| %>
    <%= link_to edit_admin_task_path(task) do %>
          <div class="items col-xs-12 col-sm-12 col-md-12 col-lg-6 clearfix test">
          <!--  <%= link_to admin_task_path(id: task.id), method: :delete, data: { confirm: 'Are you sure?' } do %>
                <span  class="delete"><i class="fa fa-times-circle fa-2x" aria-hidden="true"></i></span>
            <% end %>-->
               <div class="info-block block-info clearfix" style="border-right-color:#0FBD44;"><!--ovdje ide generisana boja-->
                  <div class="square-box pull-left">
                         <i class="fa fa-user fa-5x"></i>
                         <span class="username truncate"><%= task.user.first_name %></span>
                  </div>
                  <div class="info-box pull-right">
                    <h5 class="name1 truncate">Completed: <%= task.parcent_done%>%</h5>
                    <h4>Name: <%= task.name %></h4>
                    <p class="name1 truncate">Description: <%= task.description %></p>
                    <p>Estimate: <%= task.estimate %></p>
                  </div>
                </div>
              </div>
              <% end %>
              <% end %>
            </div>
          </div>
        </div>
        <script type="text/javascript">
        for (i = 0; i < $(".info-block").length; i++) { 
            var h = $(".info-block")[i].offsetHeight;
            $(".square-box")[i].style.height = h + "px";
          }
          
        </script>

app/views/admin/tasks/resource_report.html.erb
<%= form_tag(resource_report_admin_tasks_path, :method => "get", remote: true) do %>
  <%= label_tag 'name', 'Date From:' %>
  <%= text_field_tag :date_from, params[:date_from], class: 'datepicker'  %>
  <%= label_tag 'name', 'Date To:' %>
  <%= text_field_tag :date_to, params[:date_to], class: 'datepicker' %>
  <%= submit_tag "Search", :name => nil %>
<% end %>

<div id='resource_search_results'>
</div>

app/views/admin/tasks/resource_report.js.erb
	$('#resource_search_results').html('<%= j render "admin/tasks/resource_report"  %>')
	//alert('ovo radi definitivno12')

app/views/admin/tasks/search.html.erb
<div class="container">
  <div class="row task_form">
    <div class="col-xs-12 col-sm-8 col-md-4 col-md-offset-4">
      <div class="login-panel panel panel-default">
        <div class="panel-heading">Create new user</div>
          <div class="panel-body">       
			<div class="form-inline">
				<%= form_tag(search_admin_tasks_path, :method => "get", :remote=> true) do  %>
				  <%= label_tag 'name', 'Date To:' %>
				  <%= collection_select :status , :task_status_id, TaskStatus.all.order(:name), :id, :name, {prompt: true},:class => "form-control"  %> 
				  <%= submit_tag :submit , {class: "btn btn-primary" } %>
				<% end %>
			</div>
          </div>
        </div>
      </div>
    </div><!-- /.col-->
  </div><!-- /.row -->
</div>

<div id ="search_results">
</div>

app/views/admin/tasks/search.js.erb
	$('#search_results').html('<%= j render "admin/tasks/search"  %>')
	//alert('ovo radi definitivno')

app/views/admin/tasks/task_resource_report.html.erb
<%= form_tag(task_resource_report_admin_tasks_path, :method => "get", :remote=> true) do  %>
        <%= label_tag 'TaskName', "TaskName" %>
        <%= collection_select :task , :task_id, Task.all.order(:name), :id, :name, prompt: true %>
  <%= submit_tag :submit %>
<% end %>

<div id ="task_resoruce_report_search_results">
</div>

app/views/admin/tasks/time_report.html.erb
<%= form_tag(time_report_admin_tasks_path, :method => "get", remote: true) do  %>
  <%= label_tag 'name', 'Date From:' %>
  <%= text_field_tag :date_from, params[:date_from], class: 'datepicker'  %>
  <%= label_tag 'name', 'Date To:' %>
  <%= text_field_tag :date_to, params[:date_to], class: 'datepicker' %>
  <%= submit_tag "Search", :name => nil %>
<% end %>

<div id='time_search_results'>
</div>

app/views/admin/tasks/time_report.js.erb
	$('#time_search_results').html('<%= j render "admin/tasks/time_report"  %>')
	//alert('ovo radi time report ')

app/views/admin/tasks/user_report.js.erb
	$('#user_search_results').html('<%= j render "admin/tasks/user_report"  %>')
	//alert('ovo radi definitivno12')