config/routes.rb
Rails.application.routes.draw do

  get 'tasks/index'

namespace :admin do
resources :tasks do
  collection do
    get 'search','user_report', 'time_report','resource_report', 'task_resource_report', 'delayed_tasks_report'
  end
end
end



namespace :admin do
  resources :users, :task_statuses, :tasks, :resources
end


#namespace :admin do
#  resources :tasks do
#    get 'search', on: :collection
#  end
#end

#resources :tasks, :only => [:search] do


#namespace :admin do
 # resources :tasks do
  #end
#end

#resources :users do
#  resources :tasks
#end

#root 'admin/users#index'
root 'sessions#new'

resource :sessions, only: [:create] 

=begin
#resource :users do
#get "/home", :to => "users#get_user_tasks"
#end
=end

#resource :users

resources :users do
  resources :tasks do
  end
end

resources :tasks do
    resource :comments
end


#get '/login', to: 'sessions#new'
#get '/logout', to: 'sessions#destroy'

  get    '/login',         to: 'sessions#new'
  post   '/login',         to: 'sessions#create'
  get    '/logout',        to: 'sessions#destroy'
  get    '/registration',  to: 'users#new'



end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :tasks
	belongs_to :user_type


  def task_status_count(status)
    self.tasks.status(status).count
  end

  #validates :password, presence: true


  #validates :password, confirmation: true

  validates :password, presence: true, confirmation: true, :unless => :already_has_password?   

private
    def already_has_password?
      !self.password_digest.blank?
    end

end

app/models/user_type.rb
class UserType < ActiveRecord::Base
	has_many :users
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController


	def index
    #@search = User.search(params[:q])
		#@users = @search.result
    @users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def edit
		@user = User.find(params[:id])
	end

	def create
		@user = User.new(user_params)
		if @user.save 
			redirect_to admin_users_path
		else
			render new
		end
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)  && @user.id != current_user.id
      flash.now[:notice] = "Post successfully created"
      render 'edit'
      
			
    elsif @user.update(user_params) && @user.id == current_user.id
      render 'edit'
		else
			render 'edit'
		end
	end

	def destroy
		@user = User.find(params[:id])
    if @user.destroy  
      flash[:notice] = 'izbrisan'
    end
	end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :password, :email, :user_type_id, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def get_user_tasks
		#@tasks = Task.all
	end
	helper_method :get_user_tasks


  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path
    else
      render new
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] =  'spasio'
      render 'edit'
    else
      flash[:notice] =  'nije'
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :password, :email, :user_type_id)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def manage_tasks_count_fo
    #user
    user.tasks.status(1).count
  end

end

app/views/users/edit.html.erb
<div class="container">
  <div class="row task_form">
    <div class="col-xs-12 col-sm-8 col-md-4 col-md-offset-4">
      <div class="login-panel panel panel-default">
        <div class="panel-heading">Create new user</div>
          <div class="panel-body">
            <%= form_for :user, url:user_path(@user), method: :patch do |f| %>
              <fieldset>
                <div class="form-group">
                  <%= f.label :first_name %><br>
                  <%= f.text_field :first_name, class: "form-control" %>
                </div>
                <div class="form-group">
                  <%= f.label :last_name %><br>
                  <%= f.text_field :last_name, class: "form-control" %>
                </div>
                <div class="form-group">
                  <%= f.label :username %><br>
                  <%= f.text_field :username, class: "form-control" %>
                </div>
                <div class="form-group">
                  <%= f.label :email %><br>
                  <%= f.text_field :email, class: "form-control" %>
                </div> 
                <div class="form-group">
                  <%= f.label :password %><br>
                  <%= f.password_field :password, class: "form-control" %>
                </div>
                <div class="form-group">
                  <%= f.label :password_confirmation %><br>
                  <%= f.password_field :password_confirmation, class: "form-control" %>
                </div> 
                <div class="form-group">
                  <%= f.submit :submit, {class: "btn btn-primary" }%>
                </div>
              </fieldset>
            <% end %>
           </div>
        </div>
      </div>
    </div><!-- /.col-->
  </div><!-- /.row -->
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row task_form">
    <div class="col-xs-12 col-sm-8 col-md-4 col-md-offset-4">
      <div class="login-panel panel panel-default">
        <div class="panel-heading">Registration</div>
          <div class="panel-body">
            <%= form_for :user, url:users_path do |f| %>
              <fieldset>
                <div class="form-group">
                  <%= f.text_field :first_name, class: "form-control", placeholder: "First name" %>
                </div>
                 <div class="form-group">
                  <%= f.text_field :last_name, class: "form-control", placeholder: "Last name" %>
                </div>
                <div class="form-group">
                  <%= f.text_field :username, class: "form-control", placeholder: "Username" %>
                </div>
                <div class="form-group">
                  <%= f.text_field :password, class: "form-control", placeholder: "Password" %>
                </div>
                <div class="form-group">
                  <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
                </div>  
                <div class="form-group">                  
                  <%= f.hidden_field :user_type_id, :value => 2 %>
                </div>
                <div class="form-group">
                	<%= f.submit :submit, {class: "btn btn-primary" }  %>
                </div>
              </fieldset>
            <% end %>
          </div>
        </div>
      </div>
    </div><!-- /.col-->
  </div><!-- /.row -->
</div>

app/views/users/user_home.html.erb
<div class="container">
	<div class="row">
		<%= link_to user_tasks_path(current_user.id,:task_status_id=>1)do %>
			<p class="col-md-6 "><i class="fa fa-list-alt" ></i>
				Draft<strong><%= current_user.task_status_count(1) %></strong></p>
		<% end %>

		<%= link_to user_tasks_path(current_user.id,:task_status_id=>2)do %>
			<p class="col-md-6 "><i class="fa fa-cog" ></i>
				InProgress<strong><%= current_user.task_status_count(2) %></strong></p>
		<% end %>

		<%= link_to user_tasks_path(current_user.id,:task_status_id=>3)do %>
			<p class="col-md-6 "><i class="fa fa-search" ></i>
				Feedback<strong><%= current_user.task_status_count(3) %></strong></p>
		<% end %>

		<%= link_to user_tasks_path(current_user.id,:task_status_id=>4)do %>
			<p class="col-md-6 "><i class="fa fa-check-square-o" ></i>
				Finished<strong><%= current_user.task_status_count(4) %></strong></p>
		<% end %>

		<%= link_to user_tasks_path(current_user.id,:task_status_id=>5)do %>
			<p class="col-md-6 "><i class="fa fa-minus-circle"></i>
				Removed<strong><%= current_user.task_status_count(5) %></strong></p>
		<% end %>
	</div>
</div>