config/routes.rb
Rails.application.routes.draw do

  get 'tasks/index'

namespace :admin do
resources :tasks do
  collection do
    get 'search','user_report', 'time_report','resource_report', 'task_resource_report', 'delayed_tasks_report'
  end
end
end



namespace :admin do
  resources :users, :task_statuses, :tasks, :resources
end


#namespace :admin do
#  resources :tasks do
#    get 'search', on: :collection
#  end
#end

#resources :tasks, :only => [:search] do


#namespace :admin do
 # resources :tasks do
  #end
#end

#resources :users do
#  resources :tasks
#end

#root 'admin/users#index'
root 'sessions#new'

resource :sessions, only: [:create] 

=begin
#resource :users do
#get "/home", :to => "users#get_user_tasks"
#end
=end

#resource :users

resources :users do
  resources :tasks do
  end
end

resources :tasks do
    resource :comments
end


#get '/login', to: 'sessions#new'
#get '/logout', to: 'sessions#destroy'

  get    '/login',         to: 'sessions#new'
  post   '/login',         to: 'sessions#create'
  get    '/logout',        to: 'sessions#destroy'
  get    '/registration',  to: 'users#new'



end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :task
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  has_many :used_resources, :class_name => "UsedResource", foreign_key: "resource_id" 
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user
	belongs_to :task_status
  has_many :comments
  has_many :used_resources
  #has_many :resources, :through => :used_resources
  has_many :subs, class_name: "Task", foreign_key: "parent_task_id" 
  belongs_to :parent, class_name: "Task"

  accepts_nested_attributes_for :used_resources
  #accepts_nested_attributes_for :resources

  validates_presence_of :name
  #validates_presence_of :estimate
  validates_presence_of :user_id
  
	scope :user_id, -> (user_id) { where user_id: user_id }
  scope :status, -> (task_status_id) { where task_status_id: task_status_id }
  scope :created_by, -> (user_id) { where created_by: user_id }
  scope :is_parent, -> (is_parent) {where is_parent: is_parent}
  scope :created_at_range, -> (start_date, end_date) { where "created_at > ? AND created_at < ? ",start_date.beginning_of_day, end_date.end_of_day}
  scope :delayed, -> {where "logged_time > estimate"}

end

app/models/task_status.rb
class TaskStatus < ActiveRecord::Base
	has_many :tasks
end

app/models/used_resource.rb
class UsedResource < ActiveRecord::Base
  belongs_to :task
  belongs_to :resource

  scope :created_at_range, -> (start_date, end_date) {where "created_at > ? AND created_at < ?", start_date.beginning_of_day, end_date.end_of_day}
  scope :used_for_task, -> (task_id) { where task_id: task_id }
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :tasks
	belongs_to :user_type


  def task_status_count(status)
    self.tasks.status(status).count
  end

  #validates :password, presence: true


  #validates :password, confirmation: true

  validates :password, presence: true, confirmation: true, :unless => :already_has_password?   

private
    def already_has_password?
      !self.password_digest.blank?
    end

end

app/models/user_type.rb
class UserType < ActiveRecord::Base
	has_many :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :task_status_count
  helper_method :task_types
  helper_method :user_name
  helper_method :resources_count
  helper_method :test

  def current_user
    if @current_user 
      @current_user
    else
      @current_user = User.find session[:user_id]
    end 
  end

  def task_status_count(status)
    @task_status_count = Task.status(status).count
  end

  def resources_count(id)
    resource = Resource.find(id)
    @resource_cont = resource.quantity
  end

  def user_name(id)
    user = User.find(id)
    @user_name = user.first_name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @task = Task.find(params[:task_id])
    @comment = @task.comments.create(comment_params)
    respond_to do |format|
    format.html { render :nothing => true }
    format.js
    end
  end

  def new
    @comment = Comment.new
      respond_to do |format|
    format.html
    format.js
  end
  end

private
    def comment_params
      params.require(:comment).permit(:body, :created_by)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def admin_home
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
  	user = User.find_by email: params[:email]
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
      session[:user_name] = user.first_name
      if user.user_type.name == 'Admin'
        log_in user
    		render 'admin/admin_home' 
      else
        render 'users/user_home'
      end
  	else
      flash[:danger] = 'Invalid email/password combination' 
  		render 'new'
  	end
  end

  def destroy
  	session[:user_id] = nil
    reset_session
  	redirect_to login_path
  end

  def new
    session[:user_id] = nil
  end

  def log_in(user)
    session[:user_id] = user.id
  end
end

if (2 == "2")
  puts "false"
elsif (1 == "2")
  puts "also false"
else
  puts "true"
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  #before_action :find_record

  def index
    if params[:task_status_id]
      @tasks = current_user.tasks.status(params[:task_status_id])  
    else
      @tasks = Task.all
    end
  end

  def show
    @task = Task.find(params[:id])
    if @task.parent_task_id 
      @parent = Task.find(@task.parent_task_id)
    else
      @parent = Task.new
    end
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def create 
      @task = Task.new(task_params)
    if @task.save
      redirect_to user_tasks_path
    else
      render 'new'
    end
  end

  def update 
    @task = Task.find(params[:id])
      if @task.update(task_params)
        respond_to do | format |
        format.html do 
        redirect_to user_tasks_path 
      end
      format.json do
        render json: @task.to_json 
      end
      end
        
    else
      render 'edit'
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to admin_tasks_path
  end

  def search
  end
  
  private
    def task_params
      params.require(:task).permit(:description, :logged_time, :parcent_done, :user_id, :task_status_id)
    end
end
    

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def get_user_tasks
		#@tasks = Task.all
	end
	helper_method :get_user_tasks


  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path
    else
      render new
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] =  'spasio'
      render 'edit'
    else
      flash[:notice] =  'nije'
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :password, :email, :user_type_id)
  end

end

app/helpers/admin/tasks_helper.rb
module Admin::TasksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def link_to_add_used_resources(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render('admin/used_resources/used_resources_new', f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end

  def nice_date_form(the_date)
   return the_date.strftime('%d-%m-%Y')
end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper

  def tasktest
    tasks.status(1).count
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def manage_tasks_count_fo
    #user
    user.tasks.status(1).count
  end

end

app/views/admin/admin_home.html.erb
<div class="container">
	<div class="row">
		<%= link_to admin_tasks_path(:task_status_id=>1) do %>
			<p class="col-md-6 squere pink"><i class="fa fa-list-alt" ></i>Draft<strong><%= task_status_count(1) %></strong></p>
		<% end %>

		<%= link_to admin_tasks_path(:task_status_id=>2) do %>
			<p class="col-md-6 squere green"><i class="fa fa-cog"></i>InProgress<strong><%= task_status_count(2) %></strong></p>
		<% end %>

		<%= link_to admin_tasks_path(:task_status_id=>3) do %>
			<p class="col-md-6 squere blue"><i class="fa fa-search"></i>Feedback<strong><%= task_status_count(3) %></strong></p>
		<% end %>

		<%= link_to admin_tasks_path(:task_status_id=>4) do %>
			<p class="col-md-6 squere yellow"><i class="fa fa-check-square-o"></i>Finished<strong><%= task_status_count(4) %></strong></p>
		<% end %>

		<%= link_to admin_tasks_path(:task_status_id=>5) do %>
			<p class="col-md-6 squere red"><i class="fa fa-minus-circle"></i>Removed<strong><%= task_status_count(5) %></strong></p>
		<% end %>
	</div>
</div>

app/views/admin/resources/_new.html.erb
<div class="container">
  <div class="row task_form">
    <div class="col-xs-12 col-sm-8 col-md-4 col-md-offset-4">
      <div class="login-panel panel panel-default">
        <div class="panel-heading">Create new resource</div>
          <div class="panel-body">
            <%= form_for :resource, url:admin_resources_path, html: {role: "form"}, remote: true do |f| %>
              <fieldset>
                <div class="form-group"> 
                  <%= f.text_field :name, class: "form-control", placeholder: "Name" , :required => true  %>
                </div> 


                <div class="form-group"> 
                  <div class="input-group number-spinner">
                    <span class="input-group-btn data-dwn">
                      <button type="button"class="btn btn-primary" data-dir="dwn" id="down"><span class="glyphicon glyphicon-minus"></span></button>
                    </span>
                    <%= f.text_field :quantity, class: "form-control", value: "1", min: "1", max: "200", placeholder: "Number" , :required => false %>
                    <span class="input-group-btn data-up">
                      <button type="button" class="btn btn-primary" data-dir="up" id="up"><span class="glyphicon glyphicon-plus"></span></button>
                    </span>
                  </div>
                </div> 

                <%= f.submit :submit, {class: "btn btn-primary" } %>
              </fieldset>
            <% end %>
          </div>
        </div>
      </div>
    </div><!-- /.col-->
  </div><!-- /.row -->
</div>

app/views/admin/resources/create.js.erb
//$('#resources').html('<%= j render 'admin/resources/index'  %>')

app/views/admin/resources/edit.html.erb
<div class="container">
  <div class="row task_form">
    <div class="col-xs-12 col-sm-8 col-md-4 col-md-offset-4">
      <div class="login-panel panel panel-default">
        <div class="panel-heading">Edit resource</div>
          <div class="panel-body">
            <%= form_for @resource, url:admin_resource_path, method: :patch  do |f| %>
              <fieldset>
                <div class="form-group"> 
                  <%= f.text_field :name, class: "form-control", placeholder: "Name" , :required => true  %>
                </div> 


                <div class="form-group"> 
                  <div class="input-group number-spinner">
                    <span class="input-group-btn data-dwn">
                      <button type="button"class="btn btn-primary" data-dir="dwn" id="down"><span class="glyphicon glyphicon-minus"></span></button>
                    </span>
                    <%= f.text_field :quantity, class: "form-control", min: "1", max: "200", placeholder: "Number" , :required => false %>
                    <span class="input-group-btn data-up">
                      <button type="button" class="btn btn-primary" data-dir="up" id="up"><span class="glyphicon glyphicon-plus"></span></button>
                    </span>
                  </div>
                </div> 

                <%= f.submit :submit, {class: "btn btn-primary" } %>
              </fieldset>
            <% end %>
          </div>
        </div>
      </div>
    </div><!-- /.col-->
  </div><!-- /.row -->
</div>

app/views/admin/resources/index.html.erb
  <div class="container">
    <div class="row">
      
      <div class="col-lg-12 margin-bottom-20">
        <input type="search" class="form-control" id="input-search" placeholder="Search Resourcecs..." >
      </div>
    </div>




        <div class="row">
          <div class="searchable-container">
  <% @resources.each do |res| %>
       <%= link_to edit_admin_resource_path(res) do %>
      
            <div class="items col-xs-12 col-sm-12 col-md-12 col-lg-6 clearfix test">

               <div class="info-block block-info clearfix" style="border-right-color:#20819E;"><!--ovdje ide generisana boja-->
                  <div class="square-box pull-left">
                         <i class="fa fa-cogs fa-5x"></i>
                         <span class="username truncate"></span>
                  </div>
                  <div class="info-box pull-right">
                    <h4><%= res.name %></h4>
                    <p>Quantity: <%= res.quantity %></p>
                  </div>
                </div>
              </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>

app/views/admin/resources/new.html.erb
<div class="container">
  <div class="row task_form">
    <div class="col-xs-12 col-sm-8 col-md-4 col-md-offset-4">
      <div class="login-panel panel panel-default">
        <div class="panel-heading">Create new resource</div>
          <div class="panel-body">
            <%= form_for :resource, url:admin_resources_path do |f| %>
              <fieldset>
                <div class="form-group"> 
                  <%= f.text_field :name, class: "form-control", placeholder: "Name" , :required => true  %>
                </div> 


                <div class="form-group"> 
                  <div class="input-group number-spinner">
                    <span class="input-group-btn data-dwn">
                      <button type="button"class="btn btn-primary" data-dir="dwn" id="down"><span class="glyphicon glyphicon-minus"></span></button>
                    </span>
                    <%= f.text_field :quantity, class: "form-control", value: "1", min: "1", max: "200", placeholder: "Number" , :required => false %>
                    <span class="input-group-btn data-up">
                      <button type="button" class="btn btn-primary" data-dir="up" id="up"><span class="glyphicon glyphicon-plus"></span></button>
                    </span>
                  </div>
                </div> 

                <%= f.submit :submit, {class: "btn btn-primary" } %>
              </fieldset>
            <% end %>
          </div>
        </div>
      </div>
    </div><!-- /.col-->
  </div><!-- /.row -->
</div>

app/views/admin/resources/show.html.erb
<div class="container">
  <div class="row task_form">
    <div class="col-xs-12 col-sm-8 col-md-4 col-md-offset-4">
      <div class="login-panel panel panel-default">
        <div class="panel-heading">Create new resource</div>
          <div class="panel-body">
            <%= form_for :resource, url:admin_resources_path do |f| %>
              <fieldset>
                <div class="form-group"> 
                  <%= f.text_field :name, class: "form-control", placeholder: "Name" , :required => true  %>
                </div> 


                <div class="form-group"> 
                  <div class="input-group number-spinner">
                    <span class="input-group-btn data-dwn">
                      <button type="button"class="btn btn-primary" data-dir="dwn" id="down"><span class="glyphicon glyphicon-minus"></span></button>
                    </span>
                    <%= f.text_field :quantity, class: "form-control", min: "1", max: "200", placeholder: "Number" , :required => false %>
                    <span class="input-group-btn data-up">
                      <button type="button" class="btn btn-primary" data-dir="up" id="up"><span class="glyphicon glyphicon-plus"></span></button>
                    </span>
                  </div>
                </div> 

                <%= f.submit :submit, {class: "btn btn-primary" } %>
              </fieldset>
            <% end %>
          </div>
        </div>
      </div>
    </div><!-- /.col-->
  </div><!-- /.row -->
</div>

app/views/layouts/_admin_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-5" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/login">Easy Task</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-5">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Manage Users', admin_users_path%><span class="sr-only">(current)</span></a></li>
        <li><%= link_to 'Manage Tasks', admin_tasks_path %></li>
        <li><%= link_to 'Create Task',  new_admin_task_path  %></li>
        <li><%= link_to 'Create User',  new_admin_user_path  %></li>
        <li><%= link_to 'Create Resources',  new_admin_resource_path  %></li>
        <li><%= link_to 'Manage Resources',  admin_resources_path  %></li>
        <li><%= link_to 'Manage Account Details', edit_admin_user_path(current_user) %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Reports<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Status Report',  search_admin_tasks_path  %></li>
            <li><%= link_to 'User Report',  user_report_admin_tasks_path  %></li>
            <li><%= link_to 'Time Report',  time_report_admin_tasks_path  %></li>
            <li><%= link_to 'Resource Report',  resource_report_admin_tasks_path %></li>
            <li><%= link_to 'Task Resource Report',  task_resource_report_admin_tasks_path %></li>
            <li><%= link_to 'Delayed Tasks Report',  delayed_tasks_report_admin_tasks_path %></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <p class="navbar-text navbar-right">Signed in as <a href="#" class="navbar-link">Tarik Admin</a></p>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_user_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-5" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Easy Task</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-5">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Manage Account Details', edit_user_path(current_user) %></li>
      </ul>
      <ul class="nav navbar-nav">
        <li><%= link_to 'Log Out', logout_path %></li>
      </ul>
      <p class="navbar-text navbar-right">Signed in as <a href="#" class="navbar-link">Tarik Developer</a></p>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Striped</title>
    <%= Gon::Base.render_data %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <%= csrf_meta_tags %>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>  
  <% if session[:user_id] != nil && current_user.user_type.name == 'Admin' %>
  <%= render "layouts/admin_navbar" %>
  <% elsif session[:user_id] != nil && current_user.user_type.name == 'Developer' %>
  <%= render "layouts/user_navbar" %>
  <% end %>

      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

    <%= yield %>

  </body>
</html>